bcgov/tenant-management-system

frontend/package-lock.json
frontend/package.json

Fix for dependabot #1
Yeehaw
---
- [Frontend](https://tenant-management-system-1-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-1-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/tenant-management-system/actions/workflows/merge.yml)

build: update and pin vite version for security vulnerability

---

backend/package-lock.json

Update vite to fix a security vulnerability (backend)
Fixes dependabot #1

build: update vite version for security vulnerability

---

frontend/src/App.vue
frontend/src/components/CreateTenancyDialog.vue
frontend/src/components/ManageTenant.vue
frontend/src/components/Tenancies.vue
frontend/src/components/TenantCard.vue
frontend/src/components/layout/AppHeader.vue
frontend/src/components/layout/AppNavigation.vue
frontend/src/views/TenantsView.vue

First step in the login work is to get the PoC pages looking more like the wireframes.
Old:
New:
---
- [Frontend](https://tenant-management-system-15-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-15-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

refactor: TMS-2207 login look and feel updates to match wireframe

---

frontend/src/components/TenantCard.vue
frontend/src/components/layout/AppNavigation.vue
frontend/tsconfig.app.json

A couple of tweaks after feedback from Shannon:
- Add vertical space under the navigation bar
- Make the tenant card background colour lighter

fix: TMS-2207 login / tenant list ui tweaks

---

backend/src/common/tms.validator.ts
backend/src/repositories/tms.repository.ts
backend/src/services/tms.service.ts

Impl for createTenant,addTenantUser,getTenant

---

backend/src/common/routes.constants.ts
backend/src/common/tms.constants.ts
backend/src/common/tms.validator.ts
backend/src/repositories/tms.repository.ts
backend/src/routes/routes.ts
backend/src/services/tms.service.ts

Assign roles to a tenant user

---

backend/Dockerfile
backend/env.sample
backend/src/common/db.connection.ts
backend/src/ormconfig.ts

Backend should be configured to conform with the pipelines crunchy configuration that is generated.
---
- [Frontend](https://tenant-management-system-26-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-26-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

refactor: Refactor backend configuration

---

frontend/src/services/keycloak.ts

Add token refresh to the frontend, now that the backend is starting to expect a token.
---
- [Frontend](https://tenant-management-system-29-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-29-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

feat: TMS-2207 jwt refresh

---

.devcontainer/post-install.sh
.vscode/launch.json

Set up the post-install script will todo for the db migrations. Added a launcher for both apps.

feat: TMS-2208 dev env improvements

---

frontend/.env.sample
frontend/README.md

fix: TMS-2208 update frontend docs

---

frontend/src/services/tenant.service.ts
frontend/src/stores/useTenantStore.ts

The tenant store was duplicating the code in the Tenant.fromApiData method. Removed debug console statements and did some minor cleanup.

refactor: TMS-2208 use api helper

---

frontend/src/components/CreateTenantDialog.vue

Did some cleanup of the tenant validation:
- Limit tenant name to 30 characters
- Clear the form when it is displayed. This is so that when the user cancels and then displays the form again, old data isn't shown

fix: TMS-2208 tenant validation

---

frontend/src/components/CreateTenantDialog.vue
frontend/src/components/ui/VBtnPrimary.vue
frontend/src/components/ui/VBtnSecondary.vue
frontend/src/plugins/vuetify.ts
frontend/src/views/TenantsView.vue

Did some updates to the look and feel of the vuetify components.

fix: TMS-2208 ux updates

---

frontend/src/App.vue
frontend/src/components/layout/AppNavigation.vue
frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/tenant/TenantHeader.vue
frontend/src/components/tenant/TenantTabs.vue
frontend/src/models/tenant.model.ts
frontend/src/views/TenantManagementView.vue
frontend/src/views/TenantsView.vue

Did a huge bunch of cleanup to more closely align with the wireframes. One big thing was to shift the layout up when possible, such as the application setting the margins for the router view.

fix: TMS-2210 update ux to match wireframe

---

frontend/src/components/tenant/TenantDetails.vue
frontend/src/plugins/vuetify.ts

Did a final round of updates to get the view matching the wireframes:
- Cancel and Save buttons
- Ministries is a DDL
- Consolidated validation so that Save can be disabled when not valid
- Changed from readonly to disabled, as readonly changes on focus, mouseover, etc
- Removed the kebab menu when editing and replaced it with an X for cancelling

fix: TMS-2210 tenant form updates

---

.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://tenant-management-system-64-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-64-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new images are …

fix: Fix pr close

---

.github/workflows/merge.yml

removed tests from merge because we are skipping tests.
---
- [Frontend](https://tenant-management-system-65-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-65-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/tenant-management-system/ac …

fix: Update merge.yml

---

.github/workflows/pr-open.yml
frontend/.env.sample
frontend/src/main.ts

this was old, keycloak doesn't need to be skipped
---
- [Frontend](https://tenant-management-system-66-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-66-frontend.apps.silver.devops.gov.bc.ca/api) …

fix: removed keycloak skip

---

.github/workflows/.update-secrets.yml

Update the secrets for issuer and jwks uri for test/prod environments
---
- [Frontend](https://tenant-management-system-67-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-67-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: Update .update-secrets.yml

---

.github/workflows/.update-secrets.yml

Fix backend authorization

---

frontend/src/services/role.service.ts
frontend/src/stores/useRoleStore.ts

A new service and store for fetching the roles from the API.

feat: TMS-2209 new service and store for the roles route

---

frontend/src/components/BaseSecure.vue
frontend/src/components/CreateTenantDialog.vue
frontend/src/components/TenantCard.vue
frontend/src/components/TenantList.vue
frontend/src/components/layout/AppHeader.vue
frontend/src/components/layout/AppNotifications.vue
frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/tenant/TenantHeader.vue
frontend/src/components/tenant/TenantTabs.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/user/UserSearch.vue
frontend/src/composables/index.ts
frontend/src/composables/useNotification.ts
frontend/src/models/index.ts
frontend/src/services/authenticated.axios.ts
frontend/src/services/index.ts
frontend/src/services/role.service.ts
frontend/src/services/tenant.service.ts
frontend/src/services/user.service.ts
frontend/src/services/utils.ts
frontend/src/stores/index.ts
frontend/src/stores/useAuthStore.ts
frontend/src/stores/useRoleStore.ts
frontend/src/stores/useTenantStore.ts
frontend/src/stores/useUserStore.ts
frontend/src/types/Notification.ts
frontend/src/types/index.ts
frontend/src/views/TenantManagementView.vue
frontend/src/views/TenantsView.vue

Added index files so that we can use barrel imports on things like models and types. Alphabetized a bunch of code to make it easier to find things.

refactor(ui): TMS-2209 filesystem cleanup

---

.github/workflows/merge.yml

referenced the wrong job, so it was failing to deploy to test/prod
---
- [Frontend](https://tenant-management-system-87-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-87-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

fix: wrong job is referenced in merge.yml

---

.github/workflows/merge.yml

Introduces a 'wait-for-approval' job that requires manual approval before deploying to production. The production deployment job now depends on this approval step to enhance deployment safety.
---
- [Frontend](https://tenant-management-system-97-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-97-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/tenant-management-system/actions …

feat: Add manual approval step before production deploy

---

charts/crunchy/values.yml

Updated the dataVolumeClaimSpec storage from 3Gi to 1Gi in the Crunchy chart values file. This change may help optimize resource usage or adapt to new storage requirements.
We currently use 118.4 MiB of 3 GiB for the pgdata and 161.1 MiB out of 300 MiB for pgwal.
It's failing to allocate enough resources for the second replica because we can't request anymore.
---
- [Frontend](https://tenant-management-system-100-frontend.apps.silver.devops.gov.bc.ca)
- …

fix: Reduce data volume storage to 1Gi in values.yml

---

.github/workflows/.deployer.yml
.github/workflows/pr-close.yml

Updated the referenced workflow version for cleanup and image promotion. Removed the cleanup_db job for removing DB users from Crunchy, this should be handled by the updated version of pr-close workflow.
---
- [Frontend](https://tenant-management-system-104-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://tenant-management-system-104-frontend.apps.silver.devops.gov.bc …

fix: Update pr-close workflow and remove cleanup_db job

---

charts/crunchy/values-pr.yml
charts/crunchy/values.yml

Updated the data volume claim storage from 300Mi to 3Gi and WAL storage from 300Mi to 1Gi in the Crunchy chart values for PR pipelines to better accommodate resource requirements. We're using one shared PostgresCluster amongst all pull requests.
---
- [Frontend](https://tenant-management-system-pr-106-frontend.apps.silver.devops.gov.bc.ca)
Please create PRs in draft mode. …

fix: Increase storage for data and WAL in values-pr.yml

---

frontend/.env.sample
frontend/README.md
frontend/src/App.vue

Updated the readme to mention the design tokens. Also fixed up the .env.sample file and its documentation.

docs(ui): TMS-2386 use design tokens

---

frontend/src/assets/styles/global.css
frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/tenant/TenantHeader.vue
frontend/src/components/tenant/TenantListCard.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/user/UserSearch.vue
frontend/src/main.ts
frontend/src/plugins/vuetify.ts
frontend/src/views/TenantManageView.vue

Put in the design tokens for the fonts and made fixes where needed. This is a first step in getting the typography configured and working, and additional work will fix up all other cases. Also did the colour conversion to the BCDS for the tenant management components. Also switched to the prefixed ("bcds..." design tokens to make it clearer what the source of the tokens it)

refactor: TMS-2508 design tokens for fonts and colours

---

frontend/src/components/layout/AppHeader.vue
frontend/src/components/tenant/TenantCreateDialog.vue
frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/tenant/TenantListCard.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/user/UserSearch.vue
frontend/src/models/ssouser.model.ts
frontend/src/models/tenant.model.ts
frontend/src/models/user.model.ts
frontend/src/services/tenant.service.ts
frontend/src/stores/useAuthStore.ts
frontend/src/views/TenantListView.vue
frontend/src/views/TenantManageView.vue

Undid an unwise design decision. The user object is now a closer match to the user+ssouser object that the API uses. This caused some grief with a datatable but everything should be functional now. This allowed the removal of some "any" types that the linter was complaining about, and the code now lints clean.
Also added a couple of early bug fixes. They're in another ticket but were getting in the way of testing.

refactor(ui): TMS-2509 add ssouser object and cleanup

---

frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/ui/LoadingWrapper.vue
frontend/src/components/user/UserSearch.vue
frontend/src/models/index.ts
frontend/src/models/tenant.model.ts
frontend/src/services/user.service.ts
frontend/src/stores/useTenantStore.ts
frontend/src/stores/useUserStore.ts
frontend/src/types/IdirSearchParameters.ts
frontend/src/types/index.ts
frontend/src/utils/constants.ts
frontend/src/utils/permissions.ts
frontend/src/views/TenantListView.vue
frontend/src/views/TenantManageView.vue

- Added RBAC using a utility function (may need more thought) and now the tenant and user management is controlled by the RBAC.
- Changed the tenant management view to not allow null for the tenant. This is a major cleanup item that will have all kinds of downstream consequences, particularly with optional chaining
- Added a loading wrapper, which will be used in all views that have data loads
- Added a TenantEditFields type so that Partial types are more rigorous
- Removed the Delete Tenant menu item until it is needed
- Cleaned up the types for the IDIR search, although maybe the more complex code is unwarranted. TBD.
- Miscellaneous code cleanup, type simplification, etc.
Please describe the tests that you ran to verify your changes. Provide …

refactor(ui): TMS-2509 rbac and code cleanup

---

frontend/src/assets/styles/global.css
frontend/src/components/tenant/TenantCreateDialog.vue
frontend/src/components/tenant/TenantDetails.vue
frontend/src/components/ui/LoadingWrapper.vue
frontend/src/services/tenant.service.ts
frontend/src/stores/useTenantStore.ts
frontend/src/views/TenantListView.vue

The "create new tenant" flow has been reworked to be "request new tenant"
- new API call to request a tenant
- new store function to call the API
- update components for the new UI design and store call

feat: TMS-2103 request new tenant

---

frontend/src/components/layout/AppNotifications.vue
frontend/src/composables/useNotification.ts
frontend/src/types/Notification.ts
frontend/src/types/NotificationType.ts
frontend/src/types/index.ts
frontend/src/views/TenantListView.vue
frontend/src/views/TenantManageView.vue

Added the title to the user notifications, and did a substantial (near-complete) redesign of the notifications interface.

feat(ui): TMS-2103 add notification title

---

frontend/package-lock.json
frontend/package.json
frontend/src/assets/styles/global.css
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/user/UserSearch.vue
frontend/src/plugins/vuetify.ts
frontend/src/views/TenantManageView.vue

Fixed up a bunch of items that were left for later:
- Made BC Sans the font for everything
- Changed the User search to display "No matching users found" if the search turns up no results
- Added background zebra stripes to the data tables
- Removed an unused tenant ID property of the user search
- Prevent searches with 1 character query terms, as the SSO API will 400 them
- Removed an unnecessary guard on the emit of the search data
- Fixed a missed rename of the TenantDetailFields type

fix(ui): TMS-2519 miscellaneous bug fixes

---

frontend/src/assets/styles/global.css
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/user/UserSearch.vue
frontend/src/stores/useTenantStore.ts
frontend/src/views/TenantManageView.vue

Fixed the final raft of UI bugs for this ticket:
- The text in disabled input fields was too light and lacked contrast
- Searching for a user and selecting a user causes the roles to appear. Doing a new search did not cause them to disappear
- Searching a user, sorting on a column, and selecting the user was causing the original sort order to take effect
- An update to tenant details was setting the store values before making the API call, and if the API call failed the erroneous values were still displayed
- Renamed the boolean loadingSearch to isLoadingSearch 

fix(ui): TMS-2519 final set of ui bugs

---

frontend/src/components/container/GroupContainer.vue
frontend/src/components/group/GroupCreateDialog.vue
frontend/src/components/group/GroupList.vue
frontend/src/components/group/GroupListCard.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/models/group.model.ts
frontend/src/models/index.ts
frontend/src/models/tenant.model.ts
frontend/src/services/group.service.ts
frontend/src/services/index.ts
frontend/src/services/tenant.service.ts
frontend/src/stores/index.ts
frontend/src/stores/useGroupStore.ts

First feature for creating groups for a tenant.
This is mostly done and merged. Outstanding work:
1. Last minute changes to the validation when the name is a duplicate
1. Need to add the user if the checkbox is selected (ran out of time)
1. Check that the display name is used for the user

feat(ui): TMS-2244 create tenant group

---

.github/workflows/.deployer.yml

updated deployer-yaml

---

.github/workflows/.deployer.yml
.github/workflows/merge.yml

Deployment fix

---

.github/workflows/.deployer.yml
.github/workflows/merge.yml

Deployment fix syntax update

---

.github/workflows/.deployer.yml
.github/workflows/merge.yml
charts/app/templates/backend-secret.yaml
charts/app/templates/backend/templates/deployment.yaml
charts/app/templates/secret.yaml
charts/app/values.yaml

Test environment fix

---

frontend/src/components/container/BaseAdminContainer.vue
frontend/src/components/container/SettingsContainer.vue
frontend/src/components/layout/AppNavigation.vue
frontend/src/models/group.model.ts
frontend/src/models/index.ts
frontend/src/models/tenant.model.ts
frontend/src/models/user.model.ts
frontend/src/router/index.ts
frontend/src/stores/useAuthStore.ts
frontend/src/utils/constants.ts
frontend/src/utils/permissions.ts

Added the additional authentication needed to use the JWT client roles to check if a user is an operations admin.
- converted the roles page to settings
- fixed the barrel imports for ssouser
- kept it simply by adding a new container for ops admin

feat(ui): TMS-2244 settings page

---

frontend/src/components/container/BaseAdminContainer.vue
frontend/src/components/container/SettingsContainer.vue
frontend/src/components/container/TenantRequestContainer.vue
frontend/src/components/tenant/TenantRequestDialog.vue
frontend/src/components/tenant/TenantUserManagement.vue
frontend/src/components/tenantrequest/TenantRequestDisplay.vue
frontend/src/models/index.ts
frontend/src/models/tenantrequest.model.ts
frontend/src/services/index.ts
frontend/src/services/tenant.service.ts
frontend/src/services/tenantrequest.service.ts
frontend/src/stores/index.ts
frontend/src/stores/useTenantRequestStore.ts
frontend/src/stores/useTenantStore.ts
frontend/src/views/TenantListView.vue

Add a new smart component for the tenant requests. The navigation is a bit tricky here, as it's the same route for both the table of requests and the request details.

feat(ui): TMS-2324 view tenant requests

---

frontend/src/components/container/TenantRequestContainer.vue
frontend/src/components/tenantrequest/TenantRequestDisplay.vue
frontend/src/models/tenantrequest.model.ts
frontend/src/services/tenantrequest.service.ts
frontend/src/stores/useTenantRequestStore.ts
frontend/src/utils/constants.ts

Added the code to approve or reject a tenant request.

feat(ui): TMS-2323 approve/reject request

---

frontend/src/__tests__/composables/useNotification.test.ts
frontend/tsconfig.vitest.json

Adding the first set of unit tests so that the Trivy tool will run correctly.

test(ui): TMS-2650 first unit tests

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/post-install.sh

With my upgrade of Windows 10 -> 11 and Ubuntu 22.04 -> 24.04, the devcontainer is complaining that SonarQube no longer has a JRE. While it doesn't really make sense that the upgrades caused this, it does highlight that the Node container doesn't have a JRE for Sonar. Let's not make every developer install it on rebuild.
Additionally:
- Fix a Trivy complaint about not using the `--no-install-recommends` flag
- Fix a Trivy complaint about the Dockerfile not having a health check
- Uncomment the database migrations so they run when the container is rebuilt

fix: TMS-2677 devcontainer tweaks

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json

One frontend package that was a Cypress dependency had a low security vulnerability and needed to be updated. Also removed a couple of unnecessary packages from the backend because they were causing warnings on install.

build(deps): TMS-2693 update dependencies
